name: Build and Deploy

on:
  push:
  
jobs:
  build:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: Install parser dependencies
        run: |
          cd parser
          npm ci
      - name: Install visualization dependencies
        run: |
          cd ../prototype1
          npm ci
      - name: Run parser and build visualization
        run: npm run pb
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          repository-name: git-visual/git-visual.github.io
          branch: gh-pages # The branch the action should deploy to.
          folder: prototype1/dist # The folder the action should deploy.
          token: ${{ secrets.TOKEN }}
