name: Build and Deploy

on: 
 - push
 - workflow_dispatch
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: Install and Build ğŸ”§
        run: |
          cd parser
          npm ci
          cd ..
          cd prototype1
          npm ci
          npm run pb

      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          repository-name: git-visual/git-visual.github.io
          branch: gh-pages # The branch the action should deploy to.
          folder: prototype1/dist # The folder the action should deploy.
          token: ${{ secrets.TOKEN }}
